sudo: true
dist: trusty

jobs:
  include:
    - stage: Build and publish Salesforce DX
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t salesforce-dx build-sfdx
      - docker images
      - docker tag salesforce-dx $DOCKER_USERNAME/salesforce-dx:v$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/salesforce-dx:v$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER
    - stage: Test
      script: docker run --rm $DOCKER_USERNAME/salesforce-dx:latest
    - stage: Set latest
      script:
      - docker tag salesforce-dx $DOCKER_USERNAME/salesforce-dx:latest
      - docker push $DOCKER_USERNAME/salesforce-dx:latest